Auth4
KCEliza/Project-Two pull request #12
Opened 2019-08-03 20:49 UTC by RachaelWhitefield

made this work on my mac.

2019-08-03 21:52 UTC, KCEliza requested changes
database name on line 14 in the config.json.

2019-08-04 00:31 UTC, KCEliza submitted a review, later dismissed

2019-08-04 00:35 UTC, KCEliza approved these changes

2019-08-04 03:58 UTC, caseyisonit approved these changes

2019-08-04 04:06 UTC, merged